/**
 * Dedicated Narrative Synthesizer for 3-Card Spreads
 * Analyzes Past, Present, and Future dynamics based on meanings.js data.
 */
const ThreeCardSynthesis = {
  // Positional metadata
  positions: ["Past / Foundation", "Present / Crucible", "Future / Trajectory"],

  /**
   * Primary entry point.
   * @param {Array} drawnCards - Array of 3 card objects generated by getCardByImageIndex()
   * @returns {Array<string>} Array containing 6 narrative paragraphs
   */
  generateReading(drawnCards, question = "") {
  if (!drawnCards || drawnCards.length !== 3) {
    return ["Unable to synthesize reading: Expected exactly 3 cards."];
  }

  const [past, present, future] = drawnCards;

  // Optional opening that acknowledges the question
  let opening = "";
  if (question) {
    opening = `In response to your question — “${question}” — `;
  }

  // Paragraph 1
    const p1 = `${opening}Your reading opens in the past position with **${past.name} (${past.orientation})**. This foundational layer was built upon ${past.details.meaning}. Historically, this established ${past.details.narrativeSnippet}, serving as the underlying catalyst for where you stand now.`;

    // Paragraph 2: Active Crucible & Present Dynamics
    const p2 = `Moving into the present, **${present.name} (${present.orientation})** takes center stage. The momentum from your foundation meets direct engagement here. You are currently navigating ${present.details.meaning}, bringing immediate focus to ${present.details.keywords.join(", ").toLowerCase()}.`;

    // Paragraph 3: Emerging Trajectory & Unfolding Outcome
    const p3 = `Looking ahead, **${future.name} (${future.orientation})** highlights the unfolding trajectory. As the lessons of ${past.name} pass through your present experience with ${present.name}, the energy shifts toward ${future.details.meaning}. This suggests an ultimate convergence around ${future.details.narrativeSnippet}.`;

    // Paragraph 4: Orientation Dynamics & Friction Analysis
    const p4 = this._analyzeOrientationFlow(past, present, future);

    // Paragraph 5: Elemental & Suit Interplay
    const p5 = this._analyzeSuitInterplay(past, present, future);

    // Paragraph 6 – Closing that ties back to the question when present
    let p6;
      if (question) {
        p6 = `**In Summary:** Regarding “${question}”, your timeline tracks an evolution from ${past.details.keywords[0].toLowerCase()} into ${present.details.keywords[0].toLowerCase()}, pointing toward ${future.details.keywords[0].toLowerCase()}. Honor the foundation laid by ${past.name} to fully step into the potential of ${future.name}.`;
      } else {
        p6 = `**In Summary:** Your timeline tracks an evolution from ${past.details.keywords[0].toLowerCase()} into ${present.details.keywords[0].toLowerCase()}, pointing toward ${future.details.keywords[0].toLowerCase()}. Honor the foundation laid by ${past.name} to fully step into the potential of ${future.name}.`;
      }
    
      return [p1, p2, p3, p4, p5, p6];
    },

  /**
   * Internal Helper: Evaluates upright vs. reversed distributions across the spread
   */
  _analyzeOrientationFlow(past, present, future) {
    const reversedCount = [past, present, future].filter(c => c.isReversed).length;

    if (reversedCount === 3) {
      return "With all three cards appearing in a reversed orientation, this spread emphasizes a period of heavy internal processing, unexpressed tension, or necessary recalibration before external progress can unfold.";
    }
    if (reversedCount === 0) {
      return "With every card drawn upright, momentum is moving forward clearly in the outer world. External decisions and direct actions will yield immediate, tangible feedback.";
    }
    if (past.isReversed && !future.isReversed) {
      return `The progression from a reversed foundation (${past.name}) to an upright trajectory (${future.name}) indicates that internal resistance or past stagnation is actively resolving, clearing the runway for outward momentum.`;
    }
    if (!past.isReversed && future.isReversed) {
      return `While your foundation (${past.name}) was outwardly active, the reversed future (${future.name}) suggests a necessary shift inward to re-examine goals and avoid uncalculated risks.`;
    }
    return `The mix of upright and reversed orientations points to an alternating rhythm between direct external action and reflective internal integration.`;
  },

  /**
   * Internal Helper: Evaluates elemental suits and Major Arcana prevalence
   */
  _analyzeSuitInterplay(past, present, future) {
    const suits = [past.suit, present.suit, future.suit];
    const majorCount = suits.filter(s => s === "Major").length;

    if (majorCount >= 2) {
      return `With ${majorCount} Major Arcana archetypes dominating this spread, overarching life lessons and fundamental spiritual shifts take precedence over minor daily routines.`;
    }

    // Check for matching suits across Past and Future
    if (past.suit === future.suit && past.suit !== "Major") {
      return `The shared elemental presence of **${past.suit}** across both past and future anchors this entire journey in a singular thematic domain. Resolving the central crucible of ${present.name} is key to mastering this elemental lesson.`;
    }

    // Check for suit diversity
    const uniqueSuits = new Set(suits);
    if (uniqueSuits.size === 3) {
      return `A varied blend of elements (${Array.from(uniqueSuits).join(", ")}) drives this spread, requiring you to remain adaptable as emotional, mental, and practical demands shift across your timeline.`;
    }

    return `To navigate this reading effectively, allow ${present.name} to serve as your active bridge—balancing the historical roots of ${past.details.keywords[0]} with the emerging pull of ${future.details.keywords[0]}.`;
  }
};
